### ISSUE TITLE
Wrong subject parameter order in replaceFirst/Last() methods

### ISSUE THREAD

**Issue by Adri1C** [voku/Stringy#13]
Hi 😃 !  

The **subject** string isn't the first, but ***the last*** parameter in these two methods from UTF8 class : 

- UTF8::str_replace_first(string $search, string $replace, string **$subject**)
- UTF8::str_replace_last(string $search, string $replace, string **$subject**)

So calls must be the same into your methods : 

- Stringy\\replaceFirst();
- Stringy\\replaceLast();

Changing this : 
```php
$str = UTF8::str_replace_first($this->str, $search, $replacement);
```
To this : 
```php
$str = UTF8::str_replace_first($search, $replacement, $this->str);
```

Here : 
- https://github.com/voku/Stringy/blob/4a128e4b5e9c2c1acd03ed2ce199be117fe9195d/src/Stringy.php#L1593
- https://github.com/voku/Stringy/blob/4a128e4b5e9c2c1acd03ed2ce199be117fe9195d/src/Stringy.php#L1608

Others methods `replace(), replaceAll(), replaceBeginning(), replaceEnding()` are fine 😉

**Comment by voku** [comment]
Thanks for the bug-report :+1:: tests are added + bug is fixed in version 4.1.1
