### ISSUE TITLE
Slugify function doesnt replace /

### ISSUE THREAD

**Issue by brightboxtech** [voku/Stringy#15]
Was using the original danielstjules repo but saw they lack updated support. So plan to use this instead. My question/issue is, when using the slugify function it doesnt replace / with a dash like I want it to. So Im having to install a whole new repo, cocur/slugify. I rather use Stringy for all my needs. So is there a way to add support for this? Example:

```
$text = 'Texttile/Machine Learning';
echo s::create($text)->slugify();
//Comes out as texttilemachine-learning, want it to come out as texttile-machine-learning
```

Can you add this additional functionality to the slugify function? Or is there something I can do on my end?

**Comment by hawezo** [comment]
Manually replacing your slashes before slugifying would be more efficient than using a whole other library for this. 

```php
$text = 'Texttile/Machine Learning';
echo s::create($text)->replace('/', '-')->slugify();
```

You could integrate this to the `slugify` method by modifying its constructor to this: 

```php
public function slugify(string $separator = '-', array $replacements = [], string $language = 'en'): self
```

I created a PR but it has to be tested before.

**Comment by voku** [comment]
@brightboxtech here is a working example in the tests: https://github.com/voku/Stringy/commit/e4af1e689ee29817c59332fb59aa16245499cd0d#diff-bd64666909b1bd3a39c621cb1153a896R1314
