### ISSUE TITLE
containsAny is not working properly

### ISSUE THREAD

**Issue by drupalista-br** [voku/Stringy#16]
Both of these calls should return TRUE

        $string = 'foo bar';
        var_dump(s($string)->containsAny(['something', 'bar', 'somethingelse']));
        var_dump(s($string)->containsAny(['something', 'foo']));

Right now both of them are returning FALSE.

**Comment by voku** [comment]
Thanks for the fix. Merged in version 5.4.10 (Portable UTF-8).
