### ISSUE TITLE
Consider extracting the ascii stuff to a separate package

### ISSUE THREAD

**Issue by GrahamCampbell** [voku/Stringy#20]
It would be wonderful if you could extract the `toAscii` to a separate packagae, and then depend on it like you do for XSS. I'd like to propose that Laravel 7 uses this package's `toAscii`, but this package currently has too many other dependencies, so I'd love to be able to only pull in `toAscii`.

**Comment by voku** [comment]
A good idea, I moved the ASCII stuff into a separated package: https://github.com/voku/portable-ascii

**Comment by GrahamCampbell** [comment]
Great, thanks!
