### ISSUE TITLE
More verbosity

### ISSUE THREAD

**Issue by dimacros** [voku/Stringy#23]
#### What is this feature about (expected vs actual behaviour)?
The tool is great, but it needs more verbosity to make its use more fluid.
#### How can I reproduce it?
Examples of methods to implement: `isEmpty`, `isNotEmpty`, `equals`, `chunk`, `format`, etc.

#### Does it take minutes, hours or days to fix?
days

#### Any additional information?

**Method list:**

• after • base64 • base64Decode • base64Encode • bcrypt • before • chunk • count • crc32 • crypt • decrypt • encoding • encrypt • equals • explode • first • format • from • hex • hexEncode • hexDecode • insensitiveMatch • in • isEmpty • isNotEmpty • isNumeric • isPrintable • isPunctuation • isWhitespace • join • kebabCase • matches • md5 • nth • pascalCase • sha1 • sha256 • similarity • strip • studlyCase • substring • to • uppercase • url • words • wrap • wrapHard • wrapSoft

**Comment by voku** [comment]
What do you mean with verbosity? Inline documentation, examples, README updates, ...?

**Comment by dimacros** [comment]
Do more methods for Stringify. I put some examples in **Method List**

**Comment by voku** [comment]
- [ ] after 
- [ ] base64 
- [ ] base64Decode 
- [ ] base64Encode 
- [ ] bcrypt
- [ ] before
- [ ] chunk
- [ ] count
- [ ] crc32
- [ ] crypt
- [ ] decrypt
- [ ] encoding
- [ ] encrypt
- [ ] equals
- [ ] explode
- [ ] first
- [ ] format
- [ ] from
- [ ] hex
- [ ] hexEncode
- [ ] hexDecode
- [ ] insensitiveMatch
- [ ] in
- [ ] isEmpty
- [ ] isNotEmpty
- [ ] isNumeric
- [ ] isPrintable
- [ ] isPunctuation
- [ ] isWhitespace
- [ ] join
- [ ] kebabCase
- [ ] matches
- [ ] md5
- [ ] nth
- [ ] pascalCase
- [ ] sha1
- [ ] sha256
- [ ] similarity
- [ ] strip
- [ ] studlyCase
- [ ] substring
- [ ] to
- [ ] uppercase
- [ ] url
- [ ] words
- [ ] wrap
- [ ] wrapHard
- [ ] wrapSoft

**Comment by voku** [comment]
@dimacros  

What do you expect from "after" and "before"? Do you need "isAfter(str1, str2)" or more something like "addAfter(searchStr, addStr)"? 

And what do you expect from "wrapHard" and "wrapSoft"? Can you add an example, thanks.

And what is with "similarity", so you mean phonetic similarity or more string like similarity?

And "nth" nth of what?

**Comment by dimacros** [comment]
The ideas of the new methods I took from the package https://twine.phlak.net/

**Comment by voku** [comment]
"from" and "to" is too generic in this use-case. So I will not add this aliases. :) Everything else is implemented and can be tested in version 6.1.0. :)
