### ISSUE TITLE
Wrong method name in doc

### ISSUE THREAD

**Issue by kip-13** [voku/Stringy#25]
#### What is this feature about (expected vs actual behaviour)?
The method name [`capitalizePersonName`](https://github.com/voku/Stringy/blob/e5e98df5ec20f1f8f9a70287b41e4927de71e4fe/README.md#capitalizepersonname--static) doesnt  exists.

`capitalizePersonalName` is the correct name.

https://github.com/voku/Stringy/blob/e5e98df5ec20f1f8f9a70287b41e4927de71e4fe/src/Stringy.php#L551

#### Does it take minutes, hours or days to fix?
Minutes.

**Comment by voku** [comment]
fixed, now we auto-generate the documentation :)
