### ISSUE TITLE
Move defuse/php-encryption to "require-dev" because unused other than Tests

### ISSUE THREAD

**Issue by cliffordp** [voku/Stringy#31]
#### What is this feature about (expected vs actual behaviour)?

Can `"defuse/php-encryption"` be moved to `"require-dev"`?

#### How can I reproduce it?

* `use Defuse\Crypto\Crypto;` in https://github.com/voku/Stringy/blob/6.4.0/src/Stringy.php#L7 was added with the original commit that added the package itself: https://github.com/voku/Stringy/commit/10ad6d33e05437446a890b408d362f5392972949
* But it's not used/called within this file, only within Tests files.
* So should it be moved to `"require-dev"`, for the sake of `composer install --no-dev`?

#### Does it take minutes, hours or days to fix?

Minutes?

#### Any additional information?

N/A

**Comment by voku** [comment]
It's used for ```Stringy->decrypt()``` and for ```Stringy->encrypt()```. Is there another reason to remove / move it?

**Comment by cliffordp** [comment]
Ah, ok, thanks for confirming it's used. No other reasons. Thanks for this library and the help.
