### ISSUE TITLE
About regex Extraction string

### ISSUE THREAD

**Issue by shenmadouyaowen** [voku/Stringy#38]
#### What is this feature about (expected vs actual behaviour)?

Hello, is there a regex string extraction function? I don't seem to have seen it. If anyone sees it, please give me a link. Thank you

**Comment by voku** [comment]
@shenmadouyaowen What do you expect that the function should do?

**Comment by shenmadouyaowen** [comment]
I need to extract Chinese, but I can't reach my expectation when I use function mb_ereg to extract,
```
$text="通过网络相互连接的云服务器、激光投影电视机（51）音响（11）设置在室内";
mb_ereg("[\\(\\（][^\\u4e00-\\u9fa5]+[\\)\\）]",$text,$arr);//Brackets may be () and（）
print_r($arr);
#Get（51） 
Array
(
    [0] => （51）
)
but what I want is （51）and （11）
Array
(
    [0] => （51）,
    [1] => （11）,
)

preg_match_all("/[\\(\\（].*?[\\)\\）]/u",$str,$matches3);//This can get the result I want （51）and （11）
```
I mean, can you improve the regex function to extract characters,Thank you

**Comment by shenmadouyaowen** [comment]
> @shenmadouyaowen Why do you not use your "preg_match_all" example if this is your expected result?
> 
> PS: Maybe you can use this tool to test your regex: e.g. https://regex101.com/r/gYGTgy/1

Although it meets my expectations, I like to use your plug-in😁,Thank you for the URL
